### ISSUE TITLE
Problem following basic tutorial

### ISSUE THREAD

**Issue by michaelGregoire** [GridPresence/GenerIter#3]
Hi. Thank you for such an interesting project. I'm eager to dig into it to see what I can do!

However, I've just hit an error while running through the Basic tutorial when trying to run the generiter command:

`generiter -L inventory.json -C compose.json`

Here's the stack trace:
```
Traceback (most recent call last):
  File "/usr/local/bin/generiter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/GenerIter/app/clep_generator.py", line 5, in main
    app = Generator()
  File "/usr/local/lib/python3.9/site-packages/GenerIter/app/clibase.py", line 19, in __init__
    self.process()
  File "/usr/local/lib/python3.9/site-packages/GenerIter/app/generator.py", line 126, in process
    factory.process()
  File "/usr/local/lib/python3.9/site-packages/GenerIter/factory.py", line 62, in process
    self._method()
  File "/usr/local/lib/python3.9/site-packages/GenerIter/processor/Basic.py", line 52, in beatsbassdrone
    drums_audio = self.getsegment(drums_sample, drums_vol_range, declick)
  File "/usr/local/lib/python3.9/site-packages/GenerIter/process.py", line 82, in getsegment
    if muted > 0:
TypeError: '>' not supported between instances of 'tuple' and 'int'
```

macOS 10.14.6
Python 3.9.1

**Comment by GridPresence** [comment]
Hi Michael,

Please can you send a copy of your compose.json file?

Cheers,

Jeremy

**Comment by michaelGregoire** [comment]
Absolutely, here you go…
[compose.json.zip](https://github.com/GridPresence/GenerIter/files/5978500/compose.json.zip)

**Comment by GridPresence** [comment]
Hi Michael,

That looks okay. I’ll try and reproduce the problem tomorrow and see what’s going wrong.

Cheers,

Jeremy

**Comment by michaelGregoire** [comment]
Thanks Jeremy.

**Comment by GridPresence** [comment]
Found it.

Looks like I was so busy creating a general solution for the advanced cases, introduced a regression on the basic cases with a type change on the **Process.getsegment()** interface.

In fact, if I look at the later algorithms, I abandon **getsegment()** altogether because it's doing too much that I don't always want it to do. It's a coding error that exposes a design flaw.

**Comment by michaelGregoire** [comment]
Nice, thanks for digging into this and taking care of it.
